daemon:
    name: Toontown BR Client Astron Cluster

general:
    eventlogger: 127.0.0.1:7100
    dc_files:
        - ../../phase_3/etc/otp.dc
        - ../../phase_3/etc/toon.dc

messagedirector:
    bind: 127.0.0.1:7101

uberdogs:
    - class: CentralLogger
      id: 4688
      anonymous: false

    - class: AvatarFriendsManager
      id: 4686
      anonymous: false

    - class: TTPlayerFriendsManager
      id: 4687
      anonymous: false

    - class: TTSpeedchatRelay
      id: 4712
      anonymous: false

    - class: DistributedDeliveryManager
      id: 4683
      anonymous: false

    - class: TTCodeRedemptionMgr
      id: 4695
      anonymous: false

    - class: ClientManager
      id: 4670
      anonymous: true

    - class: ToontownFriendsManager
      id: 4707
      anonymous: false
  
    - class: ToontownChatManager
      id: 4681
      anonymous: false

roles:
    - type: clientagent
      bind: 0.0.0.0:6667
      version: "sv1.4.40.32"
      client:
       relocate: true
       add_interest: enabled
       send_hash: false
       send_version: false
      channels:
        min: 1000000000
        max: 1009999999

    - type: stateserver
      control: 4002

    - type: database
      control: 4003
      generate:
        min: 100000000
        max: 399999999
      backend:
        type: yaml
        directory: ../databases/astrondb

    - type: dbss
      database: 4003
      ranges:
        - min: 100000000
          max: 399999999

    - type: eventlogger
      bind: 127.0.0.1:7100
      output: ../logs/events-%y%m%d_%H%M%S.log
